---
title: "Exemplo de Post Poliglota"
description: |
  A new article created using the Distill format.
author:
  - name: Nora Jones 
    url: https://example.com/norajones
    affiliation: Spacely Sprockets
    affiliation_url: https://example.com/spacelysprokets
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    self_contained: false
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Distill is a publication format for scientific and technical writing, native to the web. 

Learn more about using Distill for R Markdown at <https://rstudio.github.io/distill>.

## Gráfico

```{r}
curve(dnorm, to = -3, from = 3)
```

## Código no R

```{r, layout="l-body-outset"}
library(rmarkdown)
paged_table(mtcars)
```

## Código no Python

```{python}
import pandas as pd

r.mtcars
```

```{python}
obj_do_python = "alo mãe " + "to no python!"
obj_do_python
```

## Código em SQL

### Colocando uma tabelinha no SQLite

```{r}
library(DBI)
library(dplyr)
db <- dbConnect(RSQLite::SQLite(), dbname = "sql.sqlite")

copy_to(db, mtcars)

```

### Fazendo uma consulta no SQLite

```{sql, connection=db}
SELECT * FROM mtcars
```

## Um mapinha

```{r}
library(leaflet)
leaflet() %>%
  addTiles() %>%  
  addMarkers(lng=174.768, lat=-36.852, popup="Onde o R Nasceu")
```


## Um gráfico que mexe

```{r}
library(dygraphs)
dygraph(ldeaths)
```


## Um plotly

```{r}
library(plotly)
plot_ly(z = ~volcano) %>% 
  add_surface()  
```

